name: Publish

on:
  schedule:
    - cron: '43 03 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GH Pages Build
        run: |
          gh api https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pages/builds --method POST
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}