name: Publish

on:
  schedule:
    - cron: '25 03 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GH Pages Build
        run: |
          gh api https://api.github.com/repos/jeremysbrain/jeremysbrain.github.io/pages/builds --method POST
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}